### PR TITLE
Simulate NSIS onInit callback and fix IfFlag condition

### LINKED ISSUE #1347: [Bug]: Incorrect `DisplayVersion`
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

```
komac update Ethereum.geth -v 1.16.2 -u https://gethstore.blob.core.windows.net/builds/geth-windows-amd64-1.16.2-dd1ebac1.exe
```
```yaml
AppsAndFeaturesEntries:
# Correct display version is 1.16.2-dd1ebac1
# Happens on komac v2.12.0+
- DisplayVersion: 1.16.1-12b4131f
  ProductCode: Ethereum Geth
```

### LINKED ISSUE #1580: [Bug]: `placeholder` in DefaultInstallLocation
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

NSIS installers built by Tauri have `placeholder\` in their `DefaultInstallLocation`

https://launcher-files.modrinth.com/versions/0.10.25/windows/Modrinth%20App_0.10.25_x64-setup.exe
https://github.com/anomalyco/opencode/releases/download/v1.1.12/opencode-desktop-windows-x64.exe

From: https://github.com/tauri-apps/tauri/blob/897529d7a28049c9142a0f060ecd90e2e0ca8921/crates/tauri-bundler/src/bundle/windows/nsis/installer.nsi#L75-L79

```nsis
; We don't actually use this value as default install path,
; it's just for nsis to append the product name folder in the directory selector
; https://nsis.sourceforge.io/Reference/InstallDir
!define PLACEHOLDER_INSTALL_DIR "placeholder\${PRODUCTNAME}"
InstallDir "${PLACEHOLDER_INSTALL_DIR}"
```

### PR DESCRIPTION
**Pull request by pl4nty**
Fixes #1580. I noticed the flipped condition while testing `.onInit` with some extra logging. I'm not certain `I32::ZERO` means `off` because I couldn't find a reference, but all flags are initialised to zero.

`.onInit` is also used in #1579, but I think it's just calling `kernel32::IsWow64Process2` to determine `InstallDir`.

[Before/after with Modrinth](https://diffviewer.vercel.app/v2/diff#H4sIAAAAAAAAA-1djXPaurL_V3Qyr9OkNxB_8TlD31AgbV6TkIHQvDOXOxzHCNCNsX1tkY_29H-_K38QQ4AksiHQKtMmYEmrlfTb1UrWrn7smSNvr7xXb3zqfEY39lg3ymXd0s0Hj3jhp-_YLSMHZ2-x6xHb6hFrYFd-dPeOiYm_Bc-6e2XU3ZOyspRVct29Q_hy4dr9iUGXZzjFQ92s2c6DS4YjGmSYKXquj3Hw-Mzuu8SiI1R1nCALq7uOPcMlDp2Sn832s-t2rSXtIpZHddME3spliz1BA-J6tDfCeh-7PXsw8DCt5JSCmp9Jqfhfgs_oBxqY-hDKfvG_H7Mv-9LBIQKKQL-M6vD8E8aD84lpevaAnsDTQ2Ria0hHUEdIs4yKkqQV4wnAWm9gm6Z9R6xhr69TvYxKpbykqir6idj3GIt57TUNLUeVemRo6XTi4so_S-ohkvx_slKMPhbhkwwJSk45RCr81-Dxv7iqMuyx42KP4aBy-n2s7w9008MHiHg9zzZJv0LdCZ7mwv1oGDzyHVcUWStoRbWgya8az3C8vkRDFebouXhIPOo-9Fzbpr0b_FBGJ6riD9uTLJDac6i7Isetbk7wbJ5r3bgZuvbE6vcM27TdnhykZeRFicriRIrvaZAjlm7awx4Aom_f9ebpLM41sIHRJbl0azjRh7hH9WsT-z0dpGqyxpKJgS0PL60nB3kMu497vjogNHhezMkzz0FsvIlhwJgG6XJOKs5nGOggyf0YZ1HqxAME6Ne2OyUuxVKHExKvWCnOpWFrEc2xDVR79i3DFjaY4liQCVLJ4KEXjXWfuAsyedjsGSPoRLwg0cXXDFxPmhaRpA8Ohi75ZwSZ3_lvppg_-Ndj10Bvw8DYbkzw1FL-YFEGfULtnu4406HWfHSBXPYmVpTdGBEzPgRzqfZ4rFvz6SA9cWyp-eIBetVkUg5nyjK6doE80-FMoCvRPIBOghKo_eBRPEa3alYqvqoC-E4BeWE9Fd7ysU6tOKZu4JFtgrrsdmdm0teo3TYZT0ydQpN9aUD4HhsTJmgIlBEKhQ5JMFk3dNd8qI2wcePBvP8a5rEFqreMWhhmL2sN3MnA3RW-_kbwncLHWg2elpFcKko8pduY1jEF5eFdsEFgdgWybAtz0aJubeww4-jCnAwhW3fPN7MQ_k8ZhsHCjM3Sq6ZW_v6PSjbuqasblNlwcc66gThk-6aZVrdd23TEQ-ti4o0YazfYtbCpKuXyZ0xrE9eFdLBO2ZS2f-BkuZHLzAfs1k9PoaqnrffxgwTwBPAAeCfelX2X10LUKfuOd_iBSOzXwbahL2L-b6E1BXgXgHffycg-eLcOuQJ6Ow69Z6FxYtG81nT49JrtrBPWj0P-khrYNloIB1mSVR8RXKhtYb0P3dZm6ywJffna-LN32qxVT3tn1dqXk_MGajePL6-qrUa3e9W8ymuqcg42M6wNiOHabBnT7Tb6Q9xx-rCW6HZrJgHC0Ok_jlVJLihKPnPcUKoZTSnlMsVP9eOMJNXUaqlaaGi13E_k3PIw_X8T1lPQ8Ndtej3p6QVSJcn5lLqx1mm1GueXvU670Yr14pt23OqmayoPTZApn6YES6YAj5qCTMoeDCknKuvYxNTXMu8u8dh5F-s21mmwLrtl6zLQHRMnC-s3PpEL9I6vduCLfWeZts7W6Sha9yG2g-OB1nMc7GazWTGpbGxSOW-ftPvmNkwqkT2zTiRGdYwodbzy0dHQzo6jarKGPT4a3JnEujlyjv73FP6e9CuKrGgFSU3ThHrsctQPhSHJRLmhtjyimqNCKBXuTc-pQpVTbcUUSsN12Vb5Qr1y7G8Kowx6Pc8cbFXZ_jnUzzoprJna0bbflKk_0OUII1B1yNCt9xS5EwvdETqyJxQRmkWX7gNyMZTxaSEKmac1ZoOxa7RazdZLtuCIdaubpN_zGazA5GmMgCk95BOFfK-L1_Q3CxXo2XA7lxPFmDYn9EKnvhpYvgvLS7w9wqb5TXdrtsU2oX2FqPPp1pMBU9aNe9Ag0D__BlPM72IbybKcR7oH_LfPwGQduvrYm2U_a1o3IGh9G3vovHkJnQlEUmyREezNiWl6Y9M0y9Sj-sQlPZAK09umCXsGedxT8-K5clG70TGx-uFaLdwl7njYTTKHptOERwtdCkHEzHNZzhV9C5194FMEbYBDMFhlBFow8xFoKQUhfkL83kL8vhLT3Ebxa5sYA7mcxIXtZcKrFkLhVbkELtxC4RT9OTw-7SekSEo-I8kZqYgkpZwrlTUNdS5ryfdW2l8ap6e9WvP8svH_l6gN9vKd7vobKLrnYcBGduw6unHDNe5XLqE4qgvsmHhd3e7yynwdEXz0T8tMwFKrpIWfREz5fETfN1L7fOVnrYtq7StiWNksB906HugTk54Y7GhgxM5y27o7P1yH0oYZ9phN-8iq7WDrTTjoBjVHfDThm7-8QsnXIqlw1g2P7HCNKtvKkVmxzbAf1u6z2mmdIpihqG3Yps_2WzDhVwyclKOOgX5BzpSrzTK0WEZfNZ7dvc3J6ZTt1Wh8Jf_JEdmxpumr9w-6K5KmJ-LWP1XFoDe_wfG8RHPakS8xImIvZ67807Mw6KEtGR1h7077epYtdKYT6xOxdPfBP7Ke2tsZWS4U-N_vvXhE-FvuMzvX-s1bP0kbUCceQG4x9zvBeaBCX699dqJxUweSSsx_ZJv5vphcmwRmCXcGTFuPpXAT-9Q2dEpegKctR880DSoi1vB58ZifAxO1rn7VbNXX2r5zGx6RwYPfMHn7uW1hRyduEm6j3aWUzYOI7NFZZQYC6Khdkb6io88VThsz3NiUi6UkbPHV3bgPnFMS7ICl3h-JeNrsW_IUui9llKbRecnkQ5QWpUXp9ZRuY-qfGfH81y9pLCC7s6-tFJnzPd-yF_5qQQ1e-K-wqD5kP6T1yj9p76T5kst2EsBEFBaFReEtNHd3zSx78yaXkbKTrd7YQVveEx_h-3lN4nJx2FH5P7Fo0z_q8A92xibPdcgGaByPmd_BvVbd7u2QhkfJWKe43ybfgz3ngsZpOc7afR-jNweanON_c7DSV0Tjc72peizgzDfdLaO8htLYZA_3V3Iql9tOjB-ZhSPg3NSIkVH5qYgzcM9o_W13P4xmteZpg3nv1eyai0G-_T11y8D7w-7eD0mSFNDqcgY-SMEvI_oU_Gj5n929QyLBv3v58LHMoPRcmQ9O1pUOCO9UtS632ugEW0ELj7DJuaKW1ENMCMsvIixsns58lPaHAN8Dsh_AXZJk6ToG99oiuKOsK2-dD_n8cU05VygJrAusx7Cu7G-fjp5ymMjq5yw970EcHnHOK7ngiDN8EFaZED5hla11osoX5KQT1TZqkYKsBFoEPqRKVovIcq2El7h1FORSRJbrwMBSbgsRWS5vkaVkk3EbSGJ7ZLvUmAAdm_16zn2URYF85pDrgiPCiBi2xb8zJWYBMQv8FrNAUVKTzgL8MFqiZrRIe2mc2muBo2qShViRMwyDsEeFJhKa6MWaKCf9ivZosSQHyqzIJxpLDMdiKR-R5XoTspRbLSKb0MyV0-R2ieFYx94NtecNQGE1Cl0tdPVadTUg_O2sRmFXCVkVsvpiWdXyuV_RrspJoUkBH1IlW4zIch2e5rifwmPXcmQHhN3I4wOgcsTK_53JLELGk6TZyJl_QdLKSz0Q_MyUZ0wsiikUZXxiJsXS0nA8D8n9tby5J1GXMTdFpo-wlem0WUrVNUaEYoPdaFVG98X8TPbLBweeWuH9KzNJHReUf3QoEN_rY8fE_nnAmVztka7k8mX0Xkr4856RDS84q9l94Gp-WOCPV7X6x9i_nctrAJoI9sosKYNivspPSyI09T19TJymzfrTAsxDZ9qg4CqOwl7w_ULPQGn7F5KFRMMgDkGOyHm0vBwOe4d7LveNc-lcDBdlS_3uOnHj3EJ9KG6cEzfOiRvnxI1zW_JX3Dj3G904l7XBeiEUgbVoMtWSZM3zP7Wz-unJeSNhnIGLJLsUxRzXgag397rhbfVOO1glA4xw-d-t0rNuyly7K3GnlARC06buKQ5fXmTBxt8_QBUkoX0ogF2K-6CFqY3Ug4QsFlJxm2HOQBnOkDCh11hGZm5jyTZcpZmblUqqksB9agYIXHztqBffb1n4rWeZt_FPLWl8hkgiJ9HBo1xFp3lKGtfmbMo23Xn7tzTqeJstrDph1e1I6TVYdbxSI8w6YdaJwsKsW49Zl75lluMLYJKuZda5qFcvOYnsuHWWpOnCQhMW2o6UXoOFlkRyhJUmrDRRWFhpu2Kl5XnFTFzDusmB351T2DfYtbDJDmJ_xjSMihdezrh_4GQ9XpFZ1zFpAbxfDngn3pV9l9dC1Cn7jnf4gUjs19ZFjYqY_zvJElWA95cF776TkX3wbh1yBfR2HHrPQgNWeHmt6SS5R3ldsH4c8pfUEF9cFrVEi0votG8E3_kd_8pz8E9YX3FHzDOpj8AuFbkCY8T2ABS25fHOd6gB4nWd6u_SuLEmCs_Ldyv8Cy9tXHaZZCp3aIShlHOqzI8Yfv3B4T62-ihseP4csWjHDd01H2ojbNxwm-Nr4o6B8QpfMxlThEn0W85LYiEpgLclwBMLSQHeXwS8YiEpoCcWkuktJGVJVpOsC-Lrmy9fG3_2Tpu16mnvrFr7cnLeQO3m8eVVtdXodq-aV3lNVc7BZp65eabRH-KO09cpPK6ZBAhDp_84ViW5oCj5zHFDqWY0pZTLFD_VjzOSVFOrpWqhodVyP5Fzy8N0eDORxBf3duWtMpLMFbpjQTfWOq1W4_yy12k3WrFefNOOW910jSum5HzUEqCjJI3uUscmpr6WeXeJx867WLexToN12S1bl4HumERXyHPVwvSOr3bgi31nmbbOXFZRtO5DzJnZA63nONjNZrNiUtnYpDIbQmYb7Jl1InHD10ovnicfuxz1Q2FIMlFuqC2PqOaoEEqFYRrmVKHKqbZiCsU_4rBErxz78RFQBr2eZ549VhZKAupnnRTWTO3IA37K1B_ocoQRqDpk6NZ7ityJhe4IHdkTigjNokv3AbkYyvi0EIXM0xqzwdg1Wq1m6yVbcMS61U3S7_kMVmDyNEbAlB7yiUK-18Vr-puFCvTsSVCW--xgc0IvdBqomtQ3wZcck9H51Ovy65hlOR9cx7w6gH46lzGLgz_bMFOzTIuCtW3DnP00nm560-WidqNjYvXD5Vq4UdzxsJtkGk2nCUtCNsu5MLQgfOBTBDNh7QcD7rj2cysTOVrcykqBf3F7BsOgD_En-x4oHc51JiIemzcsUF1_MOKwAjNuUPMr02M3BMaSULGDKfTI2-iRrwDAbdQjbRNjIJeTuLC9TAup4eUa8CHBdhCnDpvD49N-Qoqk5DMsYm8RSUo5VyprGupc1tZ3nKBm6p6HARvZsevooJV4qopukfbrWnGH9Hxlvo4IPvpB8CaOfzF0OvhJxJTPR_R9I7XPV37WuqjWviKGlc1y0I3imxosDGjEzsp1wpPLBA453XS4efaYff7Ire1g60046AY1R3w04Zu_WkTJ11WpcNYNg_HxDixbMcq8vhivb0FYu89tp3XKQvZS27BNn_O3YMKvGDgpx45hIWfK1WYZWiyprx3S7t7mpHXK-WpMvr4JyXHZsabpz-6LdFenzkb4XmvXLj0N-EIB5zQuX3RQ8fHt05UfKRcAEBqYUZDp7rTT544ynunE-kQs3fWjfqd4sFEuJFjjvXhQ-FvuMzvX-s2bREkbEIvY_oT7neA80Khcmmgn2jeN8l6JBXnfZr6nQf5n8LT1cAo36qM7Al4CqS0H0DQNKiLW8EVCMj8fJmpg_arZqq-1iec2PCKDB79tnIECNsltCzs6cZNwO33vnLqpMI1Jc1aZQQE6alekr-jocyXZBVZykesq5jf3oU-9P9KI4LKh1-gpdF_6QBURcERpUfpXLZ1CvKT5BWV39t2WInO-1Vx2vEEtqMHxhtW21Yfsh7TOOCSNIZTq27Adjc0jCovCW1z4rc3eXbPN3rzJZaTsZKs3dro4WUR_WZP4ArbupvyH4QslFr2wVMpzzfJA43jMnC3utep274w0PErGOsX9Nvke7EMXNE7zcdb2-xi9TdDkXILAGqscZDQ-f6NYiIu8htLYeI9CWqhcvkrxIKMsBkPy6J3izvN1acTt97kUd56vPOpW0KJLz3NFLalbnBCWX0RY2Dyd-SjtDwG-B2Q_gLskydJ1DO61RXBHWVfeOsf5-XOdcq5QElgXWI9hXdnfPh095TCR1c9Zet5tOjwLnVdywVlo-CCsMiF8wipb60SVL8hJJ6pt1CIFWQm0CHxIlawWkeVaCS_x_yjIpYgs18GBpdwWIrJcbiVLySbjNpDE9sh2qTEBOjb79ZzDLLsF_vkTsAtOESNi2Bb_5pSYCMRE8FtMBEVJTToR8MNoiabRIgWmcSqwRd65QIxLbQnDUugToU9erE-0fO5XNCxzUj5QSfAhVbLFiCzXiR2OKNDwneLsACSt5_kAqByx8n9nMouQ8SRpNj7VX5C00jSDPAh-ZkgwPhY5vEcZn1hzsbT0PKFCon8tb_dJ1Hc-VVBM2Mp02iyl6hojQrEBnQ-P74v5meyXDw48tSam6b8vhKS2YbNHEw-7Mzk7LkwK0dtpfK-PHRP7L6ZncrVHupLLl9F7KeHPe0YWrO3-xKA1uw8czY8V_PGqVv8YVBs0zWsAygj2yiwpg2KONE9LIjT1inhMnKbNenoA_EM3j6DgKo7CXvA9Fs5AmfdhZMsh0dDhMMgRuTVAP62Cwfu9wz1z5J3q19jcK-81XQJDr5voEt9TSHIfk2r-sYN-kPLzvwYohVio_wAA)

Turns out `.onInstSuccess` fixes #1347 so I thought I'd add that too. [geth before/after](https://diffviewer.vercel.app/v2/diff#H4sIAAAAAAAAA-0di3LbuPFXUHemiVtLEUk92XFndLJ8dmPHPsnOzc2po9IkJKGhCB4IOnbu7t-74EPWMxOBtCXGcDKySAAL7GIf2AWM_f3AnQQH5sFJ94fbH9EnOrVs07Q8y30MSJB8-4KZiXxcvscsINQbEm9Ej3__c8AG3oZmxAu45bpQ3zQ98QaNCAv4cIItB7MhHY0CzI-NZkvTF0qOo4f4O_odjVxrDG3PoudT8fC2cniEACLAN9EJvP8B49GH0HUDOuLn8PYIudgb8wn0kcA0UatVb1XnC2BowxF1XfqZeOOhY3HLRE2t2moaWgP9icSLuTFWK9tgaqa9BmTsWTxk-PjXlnGEKtF_TW-mX2u1I2RAQR2-G_oRghG2av-R6sqmU5_hQEzO8cWXqfV2ZLkBPkQkGAbUJc4xZyGe1cJOOg8B-YKPda3aqDaNRlXbakKTCTtL5yqpMWR4TALOHoeMUj78hB9NdG7o0bytVIHSoc_ZV2rcW26IF-vcWfanMaOh5wxt6lI21OKykrauUF9fyPEDj2vMlbt0PASOcOjn4TKcp-7nKo0ojHOlUr2mN6OKljcOrTEecuvOxRGt4wp6XRfFxMZegDf0VNJqUMemDh5GAkd4_L5a1Rbeg-QEoW3DrMbltXpruXxkERc7c2impWEALGDdUcbXFI5DMtftShH21kGcUoA5pPeCtbDNgR3XVIJSMnocplPtELamUoDdoT0BCuI1hQzfCd5aQSwFyR99DPT4NZ2y1_y7ZDQP__NEGqA2TAxlc3KnGca86D3VsEJOh5bvz-ZaVAOpHIZeWtmeEHd-BpZK6XRqecvlIDxznGU0wQgcoq2MiZkYIhPdMYAvdLiQ5-PUDqDzuAXqPwYcT9G9Ua40t-oAnjlwXtLPsWz7OZoeJ2M6IWwrNdsn09C1OOAYsT_CD9gOhWQh0D4okTJUQYODHzGfDA62Gib2QMdCH5hfhfza4hMT4MwNVApa94Ezy-anIJwC3BiGVYZRDw6QXtFrpUqzVKkhzTD1lqlV0O1NR6aTDsNA4ZOUV0VH_ctrRsfMmgaDgTwtYsD9CWhFoLOJqPhYAzz6LLvep8GBkJ0lwg2esIZSm0blzzygNueWvV9Duk1VweZRzbRFTkODtyaqNbcT1yc5OMEcrEpwzYjHxYITedTDUrA460x9gci1G46hGvC_QArh30wQVw9ko9ZqyUDuYVhUejlIZjqwAegY38WnnbLjunnR7Y4CA0jAug6DSAsJBgJ2ARMiVJ-PoSZ6e9O5No0K_DuU445etKzE7OTiAnpahz5qO_c9PIUlTC90MVIs-NpZEHTbmCoWVCy4Oxa8PblGDgls4Vc9orfwqDhQceALcaAcj-1D60hGsoHo8glmOJwWlwjrHYAsELVszZNoY73a2OkwMjav73JOd7g0bjuOMgnKJBRaqSuToEzC2mEU3STsxlVVJkGZBGUSlElQJmG194yjz8Em7CR2lMUkzITq5qzb695eDvtXnffdm2yk6GVrfvb-4jLjTMJPeTDwiY8TCSO-nWWHS68aL89Z3Yf0SEZ1d51L9Uz93HjqiQg7nIEMRJCUhSe09UKiLS_DmTrfNdo5Kp59WKi8ttZPfsmK7lr2T_TGVuc3V3voRTDbCVC90YjAbnf2dQPQ6-cA2ssXaKwgnr7MUbYpBbqHLQfWS31xzq6Czt53fxleXHXaF8PLdufs_EMX9X_p33QvB4NOyBi06VBoR11wz-BV_B2WVvGpXnQJHY4xLM-73j1h1JtCA7TMExKD_HcosNeb9WzE26BmVni0lXGS1oGs5clM2YBi3mWMsiDyqWUgxI555Jeby9OLSIDw1OePqIQ-gL8uIj2cIhZt1MrPfVWXir6k9kVOKarGqvH-r50kXWTZgF8u1MrVb24rv1n5zcpv9jPIgvKbC4m28psL3fol_eb2c_jNyht9nd5oO0dvdO04jWou_LkAstnMA-Qi6lVNy22c2gI5jVZGgV-ddqMl5UO3A_E34h-tSCRztTlLg60sjTZHfkpBNnIPd3y20niH5TloAk93GHso9B2LYwd9JnyC-AQjbjEgVoYAiCbFY2ljKcSzR4q-xVRUdSlO_5kRjsFWdB98oHxkMQTwZYsB5iCjyYhGvWKgj3OVhDTIJeV0nI-eZslEgEXpX3IK6RKoAOj_QB9gLM0jQLtDQ9dBHuXosyD3jK2XpYBTJL8EX5CvbXtUEUXV-DtrnH9UqcBhxvw93PO4gvTNAXGITkrB7ufUZiVIcR3wbK3VueCv8uWGc8HRZSf7dCrYcu4tnxi6acJq8srH3nv8-JagykOzEv3oR4i_ybqIfHOE_k7KzDhE8FmVVaZrjzXOCBoxpNQy_RwwEgxUgX8xz7hc8AwaR7-UcCjhEMLxU4jZ40dx11n3ASREyMV1--YMeJuIq-KiD15mmuB1pFX0KmL6fjK84s7vjzs7Lg1wrLvzPTeeq4LVjeqcitWbkYqVc0WXtbZhRDArEchM69N_5rXClgQUi6dWk_PQd70rlxn9Qu9JZuSd19YaDMAF9lbYpuxi7-0hOkaaht5CY8xEEAz0JkWafpitowXwK9ANKehzmwRaNY7l5xC9XyDJnEnUGlJ7b08KU5vTwVqjKa8xAeRVBPEfSCqKHccitYZU4PdlqKXlR60E26bcIZOChvN2HkjcrT3aafgwM-pPIrYoXStr9AyDzHkVuw7qS3tu68awz6GV3QmpPItv3_Ibr-nVAJkTfI9d6kdHZjilbiApPs95Z691R8bYW39rb93U6rK39i51g--n6_tomjXpm4GX-mCu74Bt3HgDsZ5TP7aLR-s7aZi6dCcSnBiIq6fLIyKunI_86-N3ov0fpRKa_Wl_8rxyYW_yfuNVE4uFC0ELUTTHNsmbdIaTx_nJgFf_hVczusHzeYrMBbUtQVbslW77oqTN7AnhIEUhg9cP8QGxWfWbRx_eesnt3wtFtwzc3QnnfmC-e4cfLIFP2abTdwu1-hNLr9VN9KaS8efNwdEBU_k0VD4NlU9D5dNQ-TS-w98qn8b3nE-jTGFRQDiC5YcrFInkyrw_wa770WLCywJCRjsyltzmjtpPk9hPuwVNfA6Lqn3YUVu_9TU_QgRr77Ztg8niYiWb8ThwNC2WMyVeepK-psufpJ8_uKrVxcHVtgAtFhMWKDXEyHjCA8TwbyHoOecv0s5sdND2QvjGEbUbWy4SE0A_hSRa_3d7vavet6iD87FHmVAGqeRH9jvCBwdbHSpXmXo2KDCVqUdl6lGGLaeDInt496fK1KNYcB9YUGXqUSy4YxZUmXoUB-6MA4t3Qktl6ll7lkTdwZ1j892nZVCZepRJeIUmQaVlUCbhuYZRdJOgMvUok6BMgjIJyiTsiUlQmXoyCJXK1PM1m6luHN6qZ3Xj8IwIKlPPS3a-a7TVjcOFbq0y9WwGqjL1qLuR9zlTj5Q4qlQ9qrFqvC-Lpx3doZktGqVS9SjHWTnO-RNBpepRjnPhHMjX2lql6lldlih3tADuqErVo1L1qFQ9ryxVz7PZCpWrJ99cPaORSNZT1SXn3HOSv3yG-XmoVLR2IppAg3maFCxMoxq_jsZ7mQxlVzE6lefm2ac2K0GK672qPDfPJr8FTZawz5exqjw3Sjh2Khwqz43izv3lTpXnRuW52YstrczoF3pDT-W52dYAqDw3m0LfCyRReW52Qy2V56aojVWem8yoqzw3uY1hn0MrKs-NynOzqRuV5-bFOTG6zjng_TiXQ6b73NMt9q9trtMR_2wxPBhcEpvRKAvN4OcoqUUwU0sfcXT5_dxdu6CEkgsJUHwNshAbEviu9fjBmuJoe31WoxTVgV9XoxGxieWiHymK_pxbiJgVYU5H0TGLWRufUU5tUH9SwvKyiM8KoTuY1PhswdcuIC4CUj-FBPOtMUPv-kVALsFAJGsS3BfhlVVB7wSDE4vHwiY0WqVZqRVh7NfhnUsCeLugJoow8jPs-hdEXDMOA09zc40Jn4R3UWounLR4N6al2XcSBCGWXEO8sCLrXdxGB99EfoetcGTYxVZQGCwFfu07GvJtkPxr-qU0pkXAM7HHaWWBqVbW6mW95DgahjWF5MU1KRYnP1_1Tl4Aj6TWpfU_GmuMgo2beOm4Ja9ve-mBf6CX1CGjxyIR-wPtYd8imRgk2RitSR1cngsCG3qGIHDshwJep3HGwwoy5A6VpsHZv8kFZ9fHi2t1PT4XUZcKY65gp-0Zdo0EO6mztwD0dCrCww_N01O5oFgStUwg7CZumKXzlxb7bsDJVJzU75Mv8ULYqDdrkleiRYOfdYfZUthm8DWP7mUiB8HmDLkbM4jtY_rcP5bS54p0ut9GafZd5NoVYGEGnNDmHerAqBY5W6Di-0Hbc05xlDc26ALLEByYoqiE5iItc00zhVkALkIzx-wJalywuJQEtb20joxbb0To4OjAnQQX1h12D8yDK0aAj2B4N_iBx1mH06JOtNXixCV__h_sR0Jr4dsAAA), although it needs the UserInfo plugin to set `InstallDir`

### CODE REVIEW

File: src/analysis/installers/nsis/entry/mod.rs [hunk 1]
```diff
@@ -504,6 +504,7 @@ impl Entry {
                 // https://github.com/mcmilk/7-Zip/blob/HEAD/CPP/7zip/Archive/Nsis/NsisIn.cpp#L3898
 
                 let value = state.get_int(data.get());
+                let value_str = value.to_string();
```
Comment (russellbanks) [inline src/analysis/installers/nsis/entry/mod.rs]:
```suggestion

                let mut buffer = itoa::Buffer::new();
```

File: src/analysis/installers/nsis/entry/mod.rs [hunk 2]
```diff
@@ -532,7 +533,7 @@ impl Entry {
                                 _ => "",
                             }
                         }
-                        _ => "",
+                        _ => value_str.as_str(),
```
Comment (russellbanks) [inline src/analysis/installers/nsis/entry/mod.rs]:
```suggestion
                        _ => buffer.format(value),
```

**Comment by russellbanks** [comment]
Is the vendor folder meant to be there?
